-- Creamos la tabla de roles
CREATE TABLE roles (
                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre                  VARCHAR(20) NOT NULL UNIQUE,
                       fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Creamos la tabla de usuarios
CREATE TABLE usuarios (
                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre                  VARCHAR(100) NOT NULL,
                          email                   VARCHAR(100) NOT NULL UNIQUE,
                          password_hash           VARCHAR(255) NOT NULL,
                          fecha_nacimiento        DATE NOT NULL,
                          genero                  VARCHAR(20) NOT NULL,
                          rol_id                  BIGINT NOT NULL REFERENCES roles(id),
                          fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Creamos la tabla de especialidades
CREATE TABLE especialidades (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nombre                  VARCHAR(100) NOT NULL UNIQUE,
                                fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Creamos la tabla de medicos
CREATE TABLE medicos (
                         id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         usuario_id              BIGINT NOT NULL UNIQUE REFERENCES usuarios(id),
                         especialidad_id         BIGINT NOT NULL REFERENCES especialidades(id),
                         fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                         fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Creamos la tabla de horarios
CREATE TABLE horarios (
                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          medico_id               BIGINT NOT NULL REFERENCES medicos(id),
                          dia_semana              VARCHAR(20) NOT NULL,
                          hora_inicio             TIME WITHOUT TIME ZONE NOT NULL,
                          hora_fin                TIME WITHOUT TIME ZONE NOT NULL,
                          fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Creamos la tabla de citas (CON AUDITORÍA)
CREATE TABLE citas (
                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       paciente_id             BIGINT NOT NULL REFERENCES usuarios(id),
                       medico_id               BIGINT NOT NULL REFERENCES medicos(id),
                       fecha_hora_inicio       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       fecha_hora_fin          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       estado                  VARCHAR(50) NOT NULL,
                       fecha_creacion          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       fecha_actualizacion     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);